// Generated by Lasy AI - https://lasy.ai
'use client';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";
import Sidebar from "@/components/custom/Sidebar";
import { usePathname } from "next/navigation";
import { useEffect, useState, useRef } from "react";
import { supabase } from "@/lib/supabase";
import { useRouter } from "next/navigation";
import { isFirstAccess } from "@/lib/storage";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const hasCheckedFunnel = useRef(false);
  
  // Páginas que não precisam de autenticação
  const publicPages = ['/auth', '/auth/reset-password'];
  const isPublicPage = publicPages.includes(pathname);

  useEffect(() => {
    // Registrar Service Worker para PWA
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker
        .register('/sw.js')
        .then((registration) => {
          console.log('Service Worker registrado com sucesso:', registration);
        })
        .catch((error) => {
          console.log('Falha ao registrar Service Worker:', error);
        });
    }

    // Verificar sessão do usuário
    const checkSession = async () => {
      try {
        const { data: { session } } = await supabase.auth.getSession();
        setIsAuthenticated(!!session);
        
        // Se não está autenticado e não está em página pública, redireciona para auth
        if (!session && !isPublicPage) {
          router.replace('/auth');
          setLoading(false);
          return;
        }
        
        // Se está autenticado e está na página de auth, redireciona para dashboard
        if (session && pathname === '/auth') {
          // Verificar se é primeiro acesso
          const firstAccess = await isFirstAccess();
          if (firstAccess && !hasCheckedFunnel.current) {
            hasCheckedFunnel.current = true;
            router.replace('/funil');
          } else {
            router.replace('/');
          }
          setLoading(false);
          return;
        }

        // Verificar se é primeiro acesso e redirecionar para funil (apenas uma vez)
        if (session && !isPublicPage && pathname !== '/funil' && !hasCheckedFunnel.current) {
          const firstAccess = await isFirstAccess();
          if (firstAccess) {
            hasCheckedFunnel.current = true;
            router.replace('/funil');
            setLoading(false);
            return;
          }
        }
        
        setLoading(false);
      } catch (error) {
        console.error('Erro ao verificar sessão:', error);
        setLoading(false);
      }
    };

    checkSession();

    // Listener para mudanças na autenticação
    const { data: { subscription } } = supabase.auth.onAuthStateChange(async (event, session) => {
      setIsAuthenticated(!!session);
      
      // Apenas redirecionar em eventos específicos
      if (event === 'SIGNED_OUT' && !isPublicPage) {
        router.replace('/auth');
      }
      
      if (event === 'SIGNED_IN' && pathname === '/auth') {
        // Verificar se é primeiro acesso
        const firstAccess = await isFirstAccess();
        if (firstAccess && !hasCheckedFunnel.current) {
          hasCheckedFunnel.current = true;
          router.replace('/funil');
        } else {
          router.replace('/');
        }
      }
    });

    return () => subscription.unsubscribe();
  }, [pathname, router, isPublicPage]);

  if (loading) {
    return (
      <html lang="pt-BR">
        <head>
          <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
          <link rel="manifest" href="/manifest.json" />
          <meta name="theme-color" content="#00E5FF" />
          <meta name="mobile-web-app-capable" content="yes" />
          <meta name="apple-mobile-web-app-capable" content="yes" />
          <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
          <meta name="apple-mobile-web-app-title" content="GestorPro" />
          <link rel="apple-touch-icon" href="/icon-192.png" />
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0D0D0D]`}>
          <div className="min-h-screen flex items-center justify-center">
            <div className="text-center">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-[#00E5FF] mx-auto mb-4"></div>
              <p className="text-gray-400 font-inter">Carregando...</p>
            </div>
          </div>
        </body>
      </html>
    );
  }

  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <title>GestorPro - Sistema de Gestão</title>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#00E5FF" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="GestorPro" />
        <link rel="apple-touch-icon" href="/icon-192.png" />
        <meta name="description" content="Sistema completo de gestão empresarial para pequenas e médias empresas" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0D0D0D]`}
      >
        {isPublicPage || pathname === '/funil' ? (
          // Páginas públicas (auth) e funil sem sidebar
          <main className="min-h-screen">
            {children}
          </main>
        ) : (
          // Páginas privadas com sidebar
          <div className="flex min-h-screen">
            <Sidebar />
            <main className="flex-1 overflow-x-hidden">
              {children}
            </main>
          </div>
        )}
      </body>
    </html>
  );
}
